### PR TITLE
WIP: molab support

### PR DESCRIPTION
**Pull request by koaning**
# Add a "run in molab" button 

This is a WIP PR for https://github.com/pymc-devs/pymc-examples/issues/809. 

CleanShot 2025-11-06 at 10 48 58

+ [x] Notebook follows style guide https://docs.pymc.io/en/latest/contributing/jupyter_style.html
+ [x] PR description contains a link to the relevant issue:
  * a tracker one for existing notebooks (tracker issues have the "tracker id" label)
  * or a proposal one for new notebooks
+ [x] Check the notebook is not excluded from any pre-commit check: https://github.com/pymc-devs/pymc-examples/blob/main/.pre-commit-config.yaml

Here's a preview of a button that is being rendered:

<a href="https://molab.marimo.io/github/pymc-devs/pymc-examples/blob/main/examples/fundamentals/data_container.ipynb" target="_blank">
Open In molab</a>

I want to check some things on the molab side to make a bit nicer, but it at least gives us a preview of what is possible. You can also generate these links yourself via https://molab.marimo.io/github. 

I will try and figure out an SVG instead of a PNG here, that should look a bit nicer.

### CODE REVIEW

**Comment by twiecki** [comment]
I tried again with the same link and same behavior.

**Comment by twiecki** [comment]
Tried again with a new molab instance and it's working now.

**Comment by fonnesbeck** [comment]
Some minor linting stuff (package version issue, maybe?).

**Comment by koaning** [comment]
@twiecki done. We will be making improvements to molab side of things as time moves forward, we just updated [the preview/landing page](https://molab.marimo.io/github/pymc-devs/pymc-examples/blob/main/examples/introductory/api_quickstart.ipynb). 

If there is feedback we'd welcome it, but those all seem to be changes needed to our backend. As-is I think we can merge, right?

**Comment by twiecki** [comment]
```
nbqa-pyupgrade................................................................................Failed
- hook id: nbqa-pyupgrade
- exit code: 1

<unknown>:30: SyntaxWarning: "\h" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\h"? A raw string is also an option.
<unknown>:30: SyntaxWarning: "\h" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\h"? A raw string is also an option.
<unknown>:28: SyntaxWarning: "\m" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\m"? A raw string is also an option.
<unknown>:28: SyntaxWarning: "\m" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\m"? A raw string is also an option.
<unknown>:27: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
<unknown>:27: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
<unknown>:20: SyntaxWarning: "\s" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\s"? A raw string is also an option.
<unknown>:20: SyntaxWarning: "\s" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\s"? A raw string is also an option.
<unknown>:13: SyntaxWarning: "\s" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\s"? A raw string is also an option.
<unknown>:36: SyntaxWarning: "\s" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\s"? A raw string is also an option.
<unknown>:13: SyntaxWarning: "\s" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\s"? A raw string is also an option.
<unknown>:36: SyntaxWarning: "\s" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\s"? A raw string is also an option.
<unknown>:34: SyntaxWarning: "\s" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\s"? A raw string is also an option.
<unknown>:34: SyntaxWarning: "\s" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\s"? A raw string is also an option.
<unknown>:28: SyntaxWarning: "\s" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\s"? A raw string is also an option.
<unknown>:28: SyntaxWarning: "\s" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\s"? A raw string is also an option.
<unknown>:30: SyntaxWarning: "\h" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\h"? A raw string is also an option.
<unknown>:28: SyntaxWarning: "\m" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\m"? A raw string is also an option.
<unknown>:27: SyntaxWarning: "\d" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\d"? A raw string is also an option.
<unknown>:20: SyntaxWarning: "\s" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\s"? A raw string is also an option.
<unknown>:13: SyntaxWarning: "\s" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\s"? A raw string is also an option.
<unknown>:36: SyntaxWarning: "\s" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\s"? A raw string is also an option.
<unknown>:34: SyntaxWarning: "\s" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\s"? A raw string is also an option.
<unknown>:28: SyntaxWarning: "\s" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\s"? A raw string is also an option.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/runner/.cache/pre-commit/reponmkmolwf/py_env-python3.14/lib/python3.14/site-packages/pyupgrade.py", line 346, in <module>
    LITERAL_TYPES = (ast.Str, ast.Num, ast.Bytes)
                     ^^^^^^^
AttributeError: module 'ast' has no attribute 'Str'
```


This is unrelated right?

**Comment by fonnesbeck** [comment]
Yes, unrelated. Will merge.

**Comment by twiecki** [comment]
@purna135 can you work with @koaning (or whoever on their side) for some joint marketing marimo/pymc.

**Comment by fonnesbeck** [comment]
Failures fixed in #815

**Comment by purna135** [comment]
Thanks, @twiecki - this sounds great!

@koaning happy to collaborate on this. I can prepare a draft announcement for LinkedIn and Twitter highlighting the "Run in Marimo" integration and how it makes PyMC examples more interactive.

Could you let me know the best way to coordinate with you - would you prefer continuing here, or should we move this to email/Slack/DMs?
